### ISSUE TITLE
Error after recent updates

### ISSUE THREAD

**Issue by FuhuXia** [HHS/ckanext-datajson#4]
The harvester extension worked fine as of mid of July 2013. During the past month CKAN core, ckanext-harvest, and ckanext-datajson have gone through quite a few changes, and now the harvester gives errors during fetch stage.

I have tested the current datajson master branch on both current ckan 2.2 and old ckan 2.1. In each case it gives similar errors, as shown below.

File "/home/ubuntu/ckan/lib/default/src/ckanext-datajson/ckanext/datajson/harvester_base.py", line 237, in import_stage
    self.package_index.index_package(pkg) 
AttributeError: 'DataJsonHarvester' object has no attribute 'package_index'

File "/home/ubuntu/ckan/lib/default/src/ckanext-datajson/ckanext/datajson/parse_datajson.py", line 4, in parse_datajson_entry
    package["title"] = datajson.get("title", defaults.get("Title"))
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by JoshData** [comment]
Hi!

I think the first issue should now be fixed in 11c5e12, but I haven't had a chance to actually try it yet.

The second issue looks odd. Off hand I'm not sure. Could you put in a debug line of some sort to figure out of it's 'datajson' or 'defaults' that is None?

I've been developing this against CKAN 2.0.1, and also with a hacked version of ckanext-harvest that makes it easier to debug what's going on (https://github.com/tauberer/ckanext-harvest/compare). So all of that could also cause the problem, maybe.

Josh

**Comment by FuhuXia** [comment]
Thanks for the info.

I did some debugging and it turned out the 'defaults' is a None. Tracing it back and it is due to the extra tab in line:
https://github.com/HHS/ckanext-datajson/blob/master/ckanext/datajson/harvester_base.py#L150

Hope it helps.
